### ISSUE TITLE
geom_hline() does not work: TypeError: unorderable types: float() > NoneType()

### ISSUE THREAD

**Issue by Make42** [yhat/ggpy#597]
If I write

    from ggplot import *
    import matplotlib.pyplot as plt
    plt.figure()
    ggplot(aes(x='date_hour', y='pageviews'), data=pageviews) + \
        geom_point() +\
        geom_hline(yintercept=[10000])

from the documentation http://ggplot.yhathq.com/docs/geom_hline.html I get the error

    Traceback (most recent call last):
      File "/home/user/anaconda2/envs/myenv/lib/python3.5/code.py", line 91, in runcode
        exec(code, self.locals)
      File "<input>", line 3, in <module>
      File "/home/user/anaconda2/envs/myenv/lib/python3.5/site-packages/ggplot/ggplot.py", line 116, in __repr__
        self.make()
      File "/home/user/anaconda2/envs/myenv/lib/python3.5/site-packages/ggplot/ggplot.py", line 636, in make
        layer.plot(ax, facetgroup, self._aes, **kwargs)
      File "/home/user/anaconda2/envs/myenv/lib/python3.5/site-packages/ggplot/geoms/geom_hline.py", line 36, in plot
        ax.axhline(y, **params)
      File "/home/user/anaconda2/envs/myenv/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 722, in axhline
        scaley = (yy < ymin) or (yy > ymax)
    TypeError: unorderable types: float() > NoneType()

My ggplot is installed with anaconda on python 3.5 from conda-forge and it's version is 0.11.5. Installed with https://anaconda.org/conda-forge/ggplot

What do I do?

**Comment by kljensen** [comment]
@Make42 the documentation is incorrect. See https://github.com/yhat/ggpy/issues/545 and https://github.com/yhat/ggpy/blob/5957a4db941be1da578ecc462d1f5b99f6d776ab/ggplot/geoms/geom_hline.py#L31. You should give `geom_hline` a parameter `y`, not `yintercept`

**Comment by Make42** [comment]
@kljensen Are you able to correct the documentation then? Or who is?

**Comment by kljensen** [comment]
@Make42  you can edit the `gh-pages` branch of this repo and submit a pull request

**Comment by vm-asd2015** [comment]
@kljensen Can you show me the file in `gh-pages` (or another branch/repo) that generates http://ggplot.yhathq.com/docs/geom_vline.html ?
