### ISSUE TITLE
ggplot installs for python3.9.1.0, but import ggplot gets error re pandas attribute tslib

### ISSUE THREAD

**Issue by jrbrearley** [yhat/ggpy#674]
ggplot-0.11.5-py2.py3-none-any.whl from pypi.org will install on python3.9.1.0 using the WinPython Control Panel. However, when I use IDLE GUI to do "import ggplot", I get the error:

Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    import ggplot
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\ggplot\__init__.py", line 19, in <module>
    from .geoms import geom_area, geom_blank, geom_boxplot, geom_line, geom_point, geom_jitter, geom_histogram, geom_density, geom_hline, geom_vline, geom_bar, geom_abline, geom_tile, geom_rect, geom_bin2d, geom_step, geom_text, geom_path, geom_ribbon, geom_now_its_art, geom_violin, geom_errorbar, geom_polygon
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\ggplot\geoms\__init__.py", line 1, in <module>
    from .geom_abline import geom_abline
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\ggplot\geoms\geom_abline.py", line 1, in <module>
    from .geom import geom
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\ggplot\geoms\geom.py", line 3, in <module>
    from ..ggplot import ggplot
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\ggplot\ggplot.py", line 13, in <module>
    from .aes import aes
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\ggplot\aes.py", line 11, in <module>
    from . import utils
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\ggplot\utils.py", line 81, in <module>
    pd.tslib.Timestamp,
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\pandas\__init__.py", line 258, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'tslib'

Is this project supported on python3? If not, please update docs at pypi.org and other places to show python2 only / deprecated.

**Comment by mb1069** [comment]
@jrbrearley A temporary solution could be to change the imports in ggplot2
https://stackoverflow.com/questions/58143253/module-pandas-has-no-attribute-tslib

This is not pretty though and could really do with a PR

**Comment by nharrisanalyst** [comment]
Pretty disappointed that this issue is over a year old and this package is unusable currently. 

Python2 has been completely depreciated.
